### ISSUE TITLE
[README] add `how to setup` project

### ISSUE THREAD

**Issue by depapp** [depapp/IndoGitHubers#1]
# description
add `how to setup` section to this `react with vite` project

**Comment by sarafurd** [comment]
Please assign this to me

**Comment by depapp** [comment]
> Please assign this to me

done!

**Comment by sarafurd** [comment]
What do you want me to put in the setup?

**Comment by sarafurd** [comment]
Do you want something like this? 

# React + Vite

This template provides a minimal setup to get React working in Vite with HMR and some ESLint rules.

Currently, two official plugins are available:

- [@vitejs/plugin-react](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md) uses [Babel](https://babeljs.io/) for Fast Refresh
- [@vitejs/plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc) uses [SWC](https://swc.rs/) for Fast Refresh

# how to setup
1. Fork the repository
2. Clone the fork
3. git clone https://github.com/<your-username>/<project-name>.git
4. cd <project-name>
5. npm install
6. npm install @vitejs/plugin-react --save-dev

**Comment by sarafurd** [comment]
In the how to setup do you want steps on how to make a pull request?

**Comment by sarafurd** [comment]
How does this look? 
# React + Vite

This template provides a minimal setup to get React working in Vite with HMR and some ESLint rules.

Currently, two official plugins are available:

- [@vitejs/plugin-react](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md) uses [Babel](https://babeljs.io/) for Fast Refresh
- [@vitejs/plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc) uses [SWC](https://swc.rs/) for Fast Refresh

# how to setup
- Fork the project
- After you've cloned your fork of the project, you will need to make a branch

```
$ git checkout -b name-of-branch
$ npm install
```

- Make any changes, save your work, and make the necessary commits 
    - Example: fixes-issue-xxx or feature-issue-xxx 
```
$ git add .
$ git commit -m "fixes-issue-xxx" 
$ git status

# Push the code to the branch you made
$ git push origin name-of-your-branch

```
- Once you've pushed your branch, don't forget to make a pull request into the `master` branch.

**Comment by depapp** [comment]
@sarafurd please raise as PR, I'll review it on the PR. thanks!

**Comment by depapp** [comment]
@sarafurd is it counted as hacktoberfest?
