### ISSUE TITLE
[🙏] - Protect main branch

### ISSUE THREAD

**Issue by mazipan** [depapp/IndoGitHubers#101]
## Describe the request

Protect `main` branch, so no one can direct push to main branch.

Steps:

- Go to `Settings` > `Rules` > `Rulesets`

<img width="336" alt="Screenshot 2024-12-10 at 09 46 17" src="https://github.com/user-attachments/assets/5d7a3677-17c2-48f8-be9a-65ff2f86b1c0">

- Fill the inputs

  - `Ruleset Name`: `main`
  - `Enforcement status`: select Active
  - SKIP `Bypass list`

- In the `Target branches`. 
  
  - Click `Add target` > Select `Include default branch`

<img width="983" alt="Screenshot 2024-12-10 at 10 00 57" src="https://github.com/user-attachments/assets/5f0124d3-415a-4375-b185-d083a946d84e">

- In the `Branch Rules`, select:
  - `Restrict deletions` (it's already checked by default in many cases)
  - `Require a pull request before merging`
    - `Required approvals`, select to `1`  
    - Select `Dismiss stale pull request approvals when new commits are pushed`
    - Select `Require conversation resolution before merging`
    - `Allowed merge methods` only `Squash`

<img width="849" alt="Screenshot 2024-12-10 at 09 58 14" src="https://github.com/user-attachments/assets/2310bc2f-bf58-4bd6-b8f4-eea16dae1e09">

  - `Require status checks to pass`
    - Check `Require branches to be up to date before merging`
    - Click `+ Add checks`
      - Find GitHub Actions: `smoke` and `ci`
      - Find Vercel Deployment
      
<img width="894" alt="Screenshot 2024-12-10 at 09 57 02" src="https://github.com/user-attachments/assets/b7bfd4ac-6b08-4968-b059-ad86f940daab">

**Comment by depapp** [comment]
please review the settings mas @mazipan 🙇🏻 

![image](https://github.com/user-attachments/assets/c9a7c7fa-a7b2-4d16-803d-d6618ac9b6af)
![image](https://github.com/user-attachments/assets/d18f4989-acf8-4276-97e1-735ae75c93ea)
![image](https://github.com/user-attachments/assets/b1bc7dc7-258d-4138-8d7d-92aba98df7f1)

i'm not sure for the `Status checks that are required` section.
is it correct?
![image](https://github.com/user-attachments/assets/74a7fc1a-46d8-46ac-8945-80d9689351a4)

**Comment by mazipan** [comment]
This is trial and error actually.
Let just ship it first, if something wrong then we can revisit the settings.

By enabling this setting, you (as an owner) also need to start to not "coding in the main branch". Consider to create separate branch then create pull request even though you can approve it by your self.
