### ISSUE TITLE
[🙏] - Setting Code Security

### ISSUE THREAD

**Issue by mazipan** [depapp/IndoGitHubers#102]
## Describe the request

Add settings for Code Security

Steps:

- Go to `Settings` > `Code Security`

<img width="337" alt="Screenshot 2024-12-10 at 10 06 40" src="https://github.com/user-attachments/assets/1f5ee382-69ae-4698-b175-ed4844631948">

- Enable `Dependency graph`
- Enable `Dependabot alerts`
- Enable `Dependabot security updates`
- Enable `Dependabot version updates`

**Comment by depapp** [comment]
i have updated the settings mas @mazipan 

![image](https://github.com/user-attachments/assets/9dbe637d-03c3-40f0-b01b-07a8beeacb72)
