### ISSUE TITLE
404 error page not found on detail page on reload

### ISSUE THREAD

**Issue by josprima-sihombing** [depapp/IndoGitHubers#21]
### Step to Reproduce:

- From homepage go to one of detail page
- on the detail page, reload

**Before reload:**
<img width="1199" alt="Screenshot 2024-11-20 at 20 50 54" src="https://github.com/user-attachments/assets/bfdbc31b-ca79-4123-8a4a-84cb9678b67f">

**After reload:**
<img width="1217" alt="Screenshot 2024-11-20 at 20 51 31" src="https://github.com/user-attachments/assets/17d6dcae-9184-40b0-ac7b-b0c4232ac38e">

**Comment by mazipan** [comment]
Add `vercel.json` in your root project should resolve the issue I guess.

**Comment by mazipan** [comment]
```json
{
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/index.html"
    }
  ]
}
```
`filename=Vercel.json`

**Comment by mazipan** [comment]
I just realized the PR is also being deployed to Netlify.

https://docs.netlify.com/routing/redirects/rewrites-proxies/#history-pushstate-and-single-page-apps

Adding `netlify.toml` can solve the Netlify problem.

```toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```
