### ISSUE TITLE
[🙏] Make the username clickable to the detail page

### ISSUE THREAD

**Issue by mazipan** [depapp/IndoGitHubers#24]
In desktop it's already there, but still missing in the mobile view

**Comment by hannahchapman79** [comment]
Hello & selemat pagi! I would like to work on this issue, please could you assign it to me?

**Comment by depapp** [comment]
> Hello & selemat pagi! I would like to work on this issue, please could you assign it to me?

@hannahchapman79 thank you for your willingness to contribute to this project. I have assigned the issue to you.

**Comment by hannahchapman79** [comment]
Thank you, I have submitted the following pull request: https://github.com/depapp/IndoGitHubers/pull/41
