### ISSUE TITLE
[🙏] Cache avatar?

### ISSUE THREAD

**Issue by mazipan** [depapp/IndoGitHubers#29]
Since we show many avatars, and most likely the URL will be same, is it possible to cache it?

For now I can only think to cache it using Service Worker. But open for other alternatives.

**Comment by Namchee** [comment]
Hi @mazipan, I'm interested in contributing for this feature. 

As for the caching strategy, I also think that SW is the way to go for this kind of data. Can I use workbox to implement this feature?
