### ISSUE TITLE
[🙏] Add sort options in mobile device

### ISSUE THREAD

**Issue by mazipan** [depapp/IndoGitHubers#30]
In desktop, we use the column header to change the sorting.

Since in the mobile we didn't use the table component, need alternatives to change the sort options.

**Comment by rhenaldkarrel** [comment]
I really want to work on this issue, but is there any reference for the expected implementation of the mobile sort view? Just to be more clear.

**Comment by mazipan** [comment]
I want to have either:
- select options contains item: by follower, by contribution

Or,

- a button, with drop-down menu.

The option will change the sort when selected.

Make it work first, we can tweak the visual later.
