### ISSUE TITLE
[🙏] add `My Open-Source Contribution on GitHub` button

### ISSUE THREAD

**Issue by depapp** [depapp/IndoGitHubers#34]
In the detail page where we already know the username, add additional `button` to open their Open-Source contribution list at https://my-open-source-contributions.vercel.app

for example: https://my-open-source-contributions.vercel.app/sandhikagalih

https://github.com/user-attachments/assets/f42e5a66-9455-4d96-9c3d-61a85c4176d4

**Comment by mazipan** [comment]
Better to rephrase the copy. 
My recommendation is: 

- See Contributions
- Check Contributions

Use "verbs" for the button action, it gives clear intent

**Comment by sandhig** [comment]
Hi! I would like to work on this issue if no one has been assigned yet?

**Comment by sandhig** [comment]
Hi, I have made a PR here: https://github.com/depapp/IndoGitHubers/pull/37

**Comment by mazipan** [comment]
Closes in #37
