### ISSUE TITLE
[🐛 ] Desktop datatable exceeds the container's width.

### ISSUE THREAD

**Issue by rhenaldkarrel** [depapp/IndoGitHubers#48]
The table behaves weirdly and exceeds the container's width on the md (768px) to xl (1280px) screen size. 
Tested on Chrome and Safari.
Below is the demo video.

https://github.com/user-attachments/assets/2ae9ff6e-7473-4f41-a941-356a74b9e210

**Comment by rhenaldkarrel** [comment]
I found the solution for this issue. May I get assigned to solve this?

**Comment by depapp** [comment]
@rhenaldkarrel assigned to you. thanks!
