### ISSUE TITLE
[🐛] The underline and text have different color

### ISSUE THREAD

**Issue by mazipan** [depapp/IndoGitHubers#49]
![Screenshot_20241122-175300_Chrome](https://github.com/user-attachments/assets/098b23fd-67cd-4795-89d6-3d2475d345e1)

Only happened in mobile device, the link and the text have different color.

Remove the `span` under the `Link`, move the className directly to the `Link` component instead.

**Comment by sarahagib** [comment]
Hi, my name is Sarah and I am a software engineering student looking for a good first issue. If no one has been assigned this issue, I would like to give it a try.

**Comment by depapp** [comment]
@sarahagib thank you for your willingness to contribute to this project. I have assigned the issue to you.

**Comment by sarahagib** [comment]
Hi, I'm so sorry I thought I would have more time to work on this, but my finals are coming up. Can I be unassigned? Sorry, and thank you.
