### ISSUE TITLE
[Frontend] re-write the project to use `components` based

### ISSUE THREAD

**Issue by depapp** [depapp/IndoGitHubers#5]
# description
- [Frontend] re-write the project to use `components` based
- please also add `Header` & `Footer` component

**Comment by Vaishali785** [comment]
Hi @depapp, I'm trying to contribute in hacktoberfest. Could you please provide some details about this project? And if this is a react project, I'd like to contribute to it.

**Comment by Kabewh** [comment]
picking this up

**Comment by depapp** [comment]
@Kabewh already approved & merged the PR.
is it counted as hactoberfest?

**Comment by Kabewh** [comment]
@depapp thanks, as of now, no, but maybe it takes a little longer to process.
