### ISSUE TITLE
[🐛] - Enable the gh-pages settings

### ISSUE THREAD

**Issue by mazipan** [depapp/IndoGitHubers#60]
## Describe the bug

Based on this log: https://github.com/depapp/IndoGitHubers/actions/runs/12000456396/job/33449607750

<img width="1013" alt="Screenshot 2024-11-25 at 06 22 41" src="https://github.com/user-attachments/assets/9dfc6359-d24b-4178-bd3c-181357bb8927">

We need to enable the gh-pages settings under https://github.com/depapp/IndoGitHubers/settings/pages. Only the owner can set this config.

<img width="1150" alt="Screenshot 2024-11-25 at 06 24 33" src="https://github.com/user-attachments/assets/3796534f-cefc-4a11-8d75-8bdac0361d85">

Set the Source from "Github Actions"

**Comment by depapp** [comment]
i have enable it mas @mazipan 
but the workflow still failed https://github.com/depapp/IndoGitHubers/actions/runs/12000456396
![image](https://github.com/user-attachments/assets/e6aa3244-f33f-4b0f-bf6f-ad6036904e13)

**Comment by mazipan** [comment]
Help to update the Source from "branch" and select gh-pages @depapp 

<img width="809" alt="Screenshot 2024-11-25 at 08 19 01" src="https://github.com/user-attachments/assets/7a84c383-902c-4ec9-82ac-8de7a26da083">

**Comment by mazipan** [comment]
I've been success deploying in https://mazipan.github.io/IndoGitHubers/

**Comment by depapp** [comment]
it's works mas @mazipan 🙇🏻 
https://depapp.github.io/IndoGitHubers/
