### ISSUE TITLE
[Frontend] add FAQ section

### ISSUE THREAD

**Issue by depapp** [depapp/IndoGitHubers#9]
# description
- add FAQ section on Footer component

**Comment by ShatilKhan** [comment]
Please assign me this issue

**Comment by ramadhanabs** [comment]
Hi @depapp please assign me this issue, thank you

**Comment by depapp** [comment]
> Please assign me this issue

done!

**Comment by depapp** [comment]
> Hi @depapp please assign me this issue, thank you

sorry @ramadhanabs , someone already commented this issue first 🙏🏻
